### ISSUE TITLE
Triforce Podcast issues

### ISSUE THREAD

**Issue by ByteBitten** [y20k/escapepod#73] opened 2021-05-09 11:46 UTC
The Triforce! Podcast seems to get the issues where the date is wrongly handled:
30 apr 2720 ep 115
20 may 2200 ep 127
3 mar 2118 ep 116
8 feb 2046 ep 155

- Add Triforce! Podcast (Two dads and a Lewis...)
- Play an episode
Issue might be after an update or restart of the app.

Expect is a correct, recent list of episodes.

Other podcasts seem unaffected.

**Screenshots**
![Screenshot_20210509-132646](https://user-images.githubusercontent.com/3299710/117570815-32618180-b0cc-11eb-938f-a2e92b37df28.png)

**Device:**
 - Device: Nokia 8
 - OS: Android 9
 - Version: Escapepod 1.0.4

**Additional context**
Escapepod stopt playing during a Triforce episode, still in 'play' state. Even after closing and removing out of memory.
Also had to reinstall earlier with a similar crash when nothing would play anymore.
I suspect only the episode that crashed the player gets it going again.

**Comment by y20k** [comment] 2021-05-10 13:44
Hi @ByteBitten 

I tried to reproduce the problem today, but I was not able to do so. For me it looks like there was something wrong with the RSS feed for that podcast (https://yogpod.libsyn.com/rss): Escapepod reads the `<pubDate>` tag within the feed and sorts episodes accordingly. I can only imagine that at the time you were updating your podcast list the podcast creator somehow messed up the pubDate. But this is just a guess. Since the problem does not seem to exist anymore, I am thinking of closing the issue.

**Comment by ByteBitten** [comment] 2021-05-14 19:06
Got the issue now again, but with 2 podcasts.
Both pulling a random episode.

One from 20 jan 2022 and one from 20 june 2022.
But with older episodes as the files.

Could it be from an earlier crash where I need to clear it fully (configs and files and all) to fix?

**Comment by y20k** [comment] 2021-06-08 19:44
I am closing this in favor of #76. The issue seems not only affect the Triforce podcast

**Closed by y20k** 2021-06-08 19:44 UTC
Labels: bug
