### ISSUE TITLE
Drops or exits with exceptions on no connectivity

### ISSUE THREAD

**Issue by lab2** [y20k/escapepod#7] opened 2019-10-08 04:42 UTC
- Deactivate Wifi or connectivity
- Add an RSS podcast feed: e.g. https://audioboom.com/channels/4986579.rss
- Click add new podcast

The app closes with an exception. In this case (see above) nothing should happen.

Android 9

**Comment by y20k** [comment] 2019-10-08 08:37
When I try to reproduce the error, I get the "Offline" dialog. I wonder which combination of network (non-)connectivity causes the crash.

![Screenshot_1570523497b](https://user-images.githubusercontent.com/9103935/66380305-730c8c80-e9b7-11e9-9486-85bfb3d8c765.png)

**Comment by y20k** [comment] 2019-10-08 09:43
I now get the crash, too! 😄 I had to use the latest release version of Escapepod to reproduce the bug. 

Interestingly I had been reworking the method that tests connectivity ([isConnectedToNetwork](https://github.com/y20k/escapepod/blob/v0.7.3/app/src/main/java/org/y20k/escapepod/helpers/NetworkHelper.kt#L70)) independently of this bug. I had to rework the method because [NetworkInfo](https://developer.android.com/reference/android/net/NetworkInfo) has been marked as deprecated.

With the new [isConnectedToNetwork](https://github.com/y20k/escapepod/blob/5353c602e9c2c95fd5b5f0b9e5b8fd9b28c0f398/app/src/main/java/org/y20k/escapepod/helpers/NetworkHelper.kt#L69) I get the mentioned `Offline` dialog. I hope that with the next release of the app the bug will be fixed for you, too.

I will leave this ticket open until the next version is released.

**Comment by lab2** [comment] 2019-10-08 09:48
Sorry, had to mention which release I was using. :) 0.7.3.8

**Comment by lab2** [comment] 2019-10-11 22:34
Retest and ok with 0.7.4.9. Great, thanks.

**Closed** 2019-10-11 22:34 UTC
Labels: bug
