### ISSUE TITLE
Lower required Android version to something more reasonable like 6.0?

### ISSUE THREAD

**Issue by Pentaphon** [y20k/escapepod#2] opened 2019-10-01 15:51 UTC
Requiring 7.1 seems a bit high for a FOSS app, no? A lot of people are still running 7.0 or lower, especially on custom ROMs with older devices. Perhaps 5.1 or 6.0 would be more reasonable?

**Comment by y20k** [comment] 2019-10-01 16:35
I know. 7.1 seems a bit high. 

I remember having a similar [discussion](https://github.com/y20k/transistor/issues/38) when I released Escapepod's sister app Transistor. The thing is: Supporting older OS versions can be a pain in the long run. And cutting support, once an app is launched, is understandable not welcomed by users.

My six year old Nexus 5 runs 7.1 (Lineage 14.1 - now discontinued). So that seemed to be a reasonable compromise. I really do not want to go lower. Especially if I am thinking say 4-5 years in the future. I have a couple of bad experiences with different code paths for different Android versions. A lot of my design decisions around Escapepod are about maintainability. The `minSdkVersion` was one of them.

**Comment by Pentaphon** [comment] 2019-10-01 17:08
I understand your hesitation, but I think a lot of users are going to get locked out of using your app. I'm not saying you should go as low as 4.x like most FOSS apps do, but requiring 6.0 at the very minimum would open up your app to a lot of users (27% of Play Store users) according to the current distribution chart, while not giving you the headaches of dealing with 4.x and 5.x. 

https://developer.android.com/about/dashboards/

**Comment by Symbian9** [comment] 2019-10-02 10:45
> ~~Lower required Android version to something more reasonable like 5.1?~~ Lower required Android version to something more reasonable like 6.0?

Hey! I want use it on *Android* `5.0` & `5.1` devices too!

**Comment by y20k** [comment] 2019-10-02 11:06
Which kind of devices / models do you want to use it on? Just curious.

**Comment by Pentaphon** [comment] 2019-10-02 13:35
I'm not really speaking for myself because my devices are at version 8.1 or higher but I know for a fact that people that I know IRL are still using phones at 5.1 and 6.0  or even 7.0 for whatever reason, especially Samsung users who are the most common users and have devices that are the most restricted to using stock ROMs and even stock custom ROMS, When I look at the distribution numbers, it lines up with what I see IRL.

So when I noticed that EscapePod is at 7.1 I thought to myself:  there's no way that FOSS app users would be ok with this because a lot of them are holding onto devices that have 6.0 or something like that because they never got LineageOS 14.1 support and they have no reason to upgrade yet because most apps out there, even on the Play Store, aren't even close to getting to 7.1 as a requirement. If anything, most FOSS apps on F-Droid still support 4.x so they are still ok. That's why I think it's a little too high. 

However, as I said before, I totally understand your desire to avoid headaches with supporting 4.x or even 5.x so I think a minimum of 6.0 would be a good compromise because that's the Android version just before many Cyanogenmod users were left behind by the fork into LineageOS. There's plenty of people on 6.0 and they won't need to update for at least another 3 years because so many FOSS apps support 4.x and up.

**Comment by Symbian9** [comment] 2019-10-02 17:30
> Which kind of devices / models do you want to use it on? Just curious.

Xiaomi Redmi 3 Pro

**Comment by y20k** [comment] 2019-10-04 19:39
I must admit that choosing Android 7.1 as the `minSdkVersion` was a gut decision at first. Now I looked a bit deeper into the matter. 

First I checked out the [API changes](https://developer.android.com/about/versions/nougat/android-7.0) Android 7 introduced and I found nothing really justifying not to lower the requirements down to Android 6.

So next thing I did: Compile a version with Android 6 support and start up an emulator. The app crashed as soon, as I added a podcast. So far not a problem. That was probably to expect.

When I saw the cause of the problem, I became more pessimistic. Escapepod is a Kotlin project that uses some Extension Functions that require the app to be configured to use Java 8 language features. That itself is not a problem. There are ways to implement a feature, without Java 8 compatibility.

Escapepod is my hobby/fun project. I started it to be teach myself Kotlin. Now seeing that parts of the language already rely on Java 8 compatibility, does not leave me optimistic for future versions of Kotlin. 

So. Sorry, but for now I am not willing to compromise. I will rather wait a year and see how the distributions numbers will develop, than to restrict my possibilities and my fun with the new language this early in the development of the app.

**Comment by Pentaphon** [comment] 2019-10-05 02:43
Fair enough, @y20k . Should I close this issue or leave it open for next year?

**Comment by y20k** [comment] 2019-10-12 13:20
Let's close this and revisit the issue next year. Thanks for the very good (but ultimately probably not satisfying) discussion!

**Closed by y20k** 2019-10-12 13:20 UTC

**Comment by NathanBnm** [comment] 2020-01-05 20:00
Let me come back to that. I think it's a shame not to support Android 6.0 because it's still a version of Android that is widely used [as Google's statistics show](https://developer.android.com/about/dashboards/). I'm still personnaly using it and I think supporting devices from Android 6 onwards is a good compromise.

But if indeed it is too much of a technical difficulty it is understandable. It's just too bad.

![image](https://user-images.githubusercontent.com/45366162/71785274-00cf3680-2ffe-11ea-8b9f-4367816e1b4b.png)
