### ISSUE TITLE
Scroll latency is very high on low end devices

### ISSUE THREAD

**Issue by lmj0011** [y20k/escapepod#39] opened 2020-07-20 04:13 UTC
**Describe the bug**
Some podcast episodes can cause sluggish UI behavior while others do not. This makes looking for next episode to play almost unbearable.

**To Reproduce**
1. Open Escapepod
2. add new podcast https://lexfridman.com/feed/podcast
3. Click cloud icon next to the latest podcast (as of now is "#109 – Brian Kernighan: UNIX, C, AWK, AMPL, and Go Programming")
4. play the podcast
5. scroll through the list of other podcasts in your library (I have 14 in my collection)
6. You will notice very sluggish scrolling (behavior persists even when audio is not playing, only goes away when changing to a media source that doesn't cause the sluggish behavior)

**Expected behavior**
scrolling to be smooth while playing podcast episode

**Screenshots**
video showing this behavior: https://www.dropbox.com/s/s76yplqc4viv5w1/VID_20200719_224539.mp4

**Device:**
 - Device: Nexus 5x
 - OS: Android 8.1 (Oreo) 
 - Version 0.9.2

**Additional context**
audio metadata for podcast episode  "#109 – Brian Kernighan: UNIX, C, AWK, AMPL, and Go Programming" from "AI Podcast with Lex Fridman":

![Screenshot from 2020-07-19 22-33-30](https://user-images.githubusercontent.com/9396189/87897109-eac01b00-ca0f-11ea-99b5-32e3db8334e9.png)

another podcast this happens with: https://podbay.fm/podcast/1474429475/e/1594735200 feed: http://feeds.feedburner.com/WaveformWithMkbhd

audio metadata for podcast episode  "Carl Pei Discusses the New OnePlus Nord & How Smartphones Are Made From Concept to Market" from Waveform: The MKBHD Podcast:

![Screenshot from 2020-07-19 23-11-11](https://user-images.githubusercontent.com/9396189/87899014-74261c00-ca15-11ea-94b7-ec2aa6752a19.png)

**Comment by lmj0011** [comment] 2020-07-24 04:30
the latency originated from the setImageURI function being called for both of the cover images in the player bottomSheet

see PR: https://github.com/y20k/escapepod/pull/40

**Comment by y20k** [comment] 2020-07-24 07:41
Thanks. Great that you found the cause of the problem!! I have a question regarding your PR (see #40).

**Comment by y20k** [comment] 2020-08-03 06:24
This issue should be fixed in [v9.0.3](https://github.com/y20k/escapepod/releases/tag/v0.9.3). Thanks for bringing this up and directly providing a solution.

**Closed by y20k** 2020-08-03 06:24 UTC
Labels: bug
